-- Proses Yeterliliği modülü: Ekipman Listesi + Yeterlilik Planı
-- Kalite ortak Supabase projesi (nnubrxbpthmkitueixbh) SQL editöründe bir kez çalıştırın.
-- msa_* tablolarıyla aynı desen: anon istemcisi okuyup yazabilsin diye RLS 'to public' açıktır.

-- ── Ekipman (makine / kalıp / hat / proses) ────────────────────────────────
create table if not exists public.cap_equipment (
  id bigint generated by default as identity primary key,
  name text not null,
  code text,
  type text,                       -- Makine / Kalıp / Hat / Proses / Cihaz
  location text,
  responsible_email text,
  description text,
  is_active boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);
alter table public.cap_equipment enable row level security;
drop policy if exists cap_equipment_all on public.cap_equipment;
create policy cap_equipment_all on public.cap_equipment for all to public using (true) with check (true);

-- ── Yeterlilik Planı (planlanan Cp/Cpk çalışmaları) ────────────────────────
create table if not exists public.cap_plan (
  id bigint generated by default as identity primary key,
  title text not null,
  equipment_id bigint references public.cap_equipment(id) on delete set null,
  equipment_name text,
  characteristic text,
  lsl numeric,
  usl numeric,
  target numeric,
  planned_date date,
  interval_months integer,         -- periyot (ay); tekrar planı için
  responsible_email text,
  status text default 'planned',   -- planned / in_progress / completed / cancelled
  study_id bigint,                 -- bağlı yeterlilik çalışması (msa_studies.id)
  notes text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);
alter table public.cap_plan enable row level security;
drop policy if exists cap_plan_all on public.cap_plan;
create policy cap_plan_all on public.cap_plan for all to public using (true) with check (true);

create index if not exists cap_plan_planned_date_idx on public.cap_plan (planned_date);
create index if not exists cap_plan_status_idx on public.cap_plan (status);
